project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: Github
        href: https://github.com/Aadyant12
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/aadyantk/
format:
  html:
    theme: minty
    css: styles.css

editor: visual

